/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ClientRouteImport } from './routes/client'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoProductsRouteImport } from './routes/no-products'
import { Route as PainelRouteRouteImport } from './routes/painel/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PainelEstatisticasRouteImport } from './routes/painel/estatisticas'
import { Route as PainelSuporteRouteImport } from './routes/painel/suporte'
import { Route as AdminClientesIndexRouteImport } from './routes/admin/clientes/index'
import { Route as AdminClientesClientIdRouteImport } from './routes/admin/clientes/$clientId'
import { Route as AdminSistemasIndexRouteImport } from './routes/admin/sistemas/index'
import { Route as AdminSistemasSystemIdRouteImport } from './routes/admin/sistemas/$systemId'
import { Route as AdminSistemasNovoRouteImport } from './routes/admin/sistemas/novo'
import { Route as AuthDiscordCallbackRouteImport } from './routes/auth.discord.callback'
import { Route as PainelSistemasSystemIdRouteImport } from './routes/painel/sistemas.$systemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoProductsRoute = NoProductsRouteImport.update({
  id: '/no-products',
  path: '/no-products',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRouteRoute = PainelRouteRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelEstatisticasRoute = PainelEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelSuporteRoute = PainelSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => PainelRouteRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientesClientIdRoute = AdminClientesClientIdRouteImport.update({
  id: '/clientes/$clientId',
  path: '/clientes/$clientId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSistemasIndexRoute = AdminSistemasIndexRouteImport.update({
  id: '/sistemas/',
  path: '/sistemas/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSistemasSystemIdRoute = AdminSistemasSystemIdRouteImport.update({
  id: '/sistemas/$systemId',
  path: '/sistemas/$systemId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSistemasNovoRoute = AdminSistemasNovoRouteImport.update({
  id: '/sistemas/novo',
  path: '/sistemas/novo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/auth/discord/callback',
  path: '/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelSistemasSystemIdRoute = PainelSistemasSystemIdRouteImport.update({
  id: '/sistemas/$systemId',
  path: '/sistemas/$systemId',
  getParentRoute: () => PainelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/painel': typeof PainelRouteRouteWithChildren
  '/client': typeof ClientRoute
  '/login': typeof LoginRoute
  '/no-products': typeof NoProductsRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/suporte': typeof PainelSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/clientes/$clientId': typeof AdminClientesClientIdRoute
  '/admin/sistemas/$systemId': typeof AdminSistemasSystemIdRoute
  '/admin/sistemas/novo': typeof AdminSistemasNovoRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/painel/sistemas/$systemId': typeof PainelSistemasSystemIdRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/sistemas/': typeof AdminSistemasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/login': typeof LoginRoute
  '/no-products': typeof NoProductsRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/suporte': typeof PainelSuporteRoute
  '/admin': typeof AdminIndexRoute
  '/painel': typeof PainelIndexRoute
  '/admin/clientes/$clientId': typeof AdminClientesClientIdRoute
  '/admin/sistemas/$systemId': typeof AdminSistemasSystemIdRoute
  '/admin/sistemas/novo': typeof AdminSistemasNovoRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/painel/sistemas/$systemId': typeof PainelSistemasSystemIdRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
  '/admin/sistemas': typeof AdminSistemasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/painel': typeof PainelRouteRouteWithChildren
  '/client': typeof ClientRoute
  '/login': typeof LoginRoute
  '/no-products': typeof NoProductsRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/painel/estatisticas': typeof PainelEstatisticasRoute
  '/painel/suporte': typeof PainelSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/clientes/$clientId': typeof AdminClientesClientIdRoute
  '/admin/sistemas/$systemId': typeof AdminSistemasSystemIdRoute
  '/admin/sistemas/novo': typeof AdminSistemasNovoRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/painel/sistemas/$systemId': typeof PainelSistemasSystemIdRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/sistemas/': typeof AdminSistemasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/painel'
    | '/client'
    | '/login'
    | '/no-products'
    | '/admin/configuracoes'
    | '/admin/logs'
    | '/admin/usuarios'
    | '/painel/estatisticas'
    | '/painel/suporte'
    | '/admin/'
    | '/painel/'
    | '/admin/clientes/$clientId'
    | '/admin/sistemas/$systemId'
    | '/admin/sistemas/novo'
    | '/auth/discord/callback'
    | '/painel/sistemas/$systemId'
    | '/admin/clientes/'
    | '/admin/sistemas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/login'
    | '/no-products'
    | '/admin/configuracoes'
    | '/admin/logs'
    | '/admin/usuarios'
    | '/painel/estatisticas'
    | '/painel/suporte'
    | '/admin'
    | '/painel'
    | '/admin/clientes/$clientId'
    | '/admin/sistemas/$systemId'
    | '/admin/sistemas/novo'
    | '/auth/discord/callback'
    | '/painel/sistemas/$systemId'
    | '/admin/clientes'
    | '/admin/sistemas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/painel'
    | '/client'
    | '/login'
    | '/no-products'
    | '/admin/configuracoes'
    | '/admin/logs'
    | '/admin/usuarios'
    | '/painel/estatisticas'
    | '/painel/suporte'
    | '/admin/'
    | '/painel/'
    | '/admin/clientes/$clientId'
    | '/admin/sistemas/$systemId'
    | '/admin/sistemas/novo'
    | '/auth/discord/callback'
    | '/painel/sistemas/$systemId'
    | '/admin/clientes/'
    | '/admin/sistemas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PainelRouteRoute: typeof PainelRouteRouteWithChildren
  ClientRoute: typeof ClientRoute
  LoginRoute: typeof LoginRoute
  NoProductsRoute: typeof NoProductsRoute
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-products': {
      id: '/no-products'
      path: '/no-products'
      fullPath: '/no-products'
      preLoaderRoute: typeof NoProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/estatisticas': {
      id: '/painel/estatisticas'
      path: '/estatisticas'
      fullPath: '/painel/estatisticas'
      preLoaderRoute: typeof PainelEstatisticasRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/suporte': {
      id: '/painel/suporte'
      path: '/suporte'
      fullPath: '/painel/suporte'
      preLoaderRoute: typeof PainelSuporteRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clientes/$clientId': {
      id: '/admin/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/admin/clientes/$clientId'
      preLoaderRoute: typeof AdminClientesClientIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sistemas/': {
      id: '/admin/sistemas/'
      path: '/sistemas'
      fullPath: '/admin/sistemas/'
      preLoaderRoute: typeof AdminSistemasIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sistemas/$systemId': {
      id: '/admin/sistemas/$systemId'
      path: '/sistemas/$systemId'
      fullPath: '/admin/sistemas/$systemId'
      preLoaderRoute: typeof AdminSistemasSystemIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sistemas/novo': {
      id: '/admin/sistemas/novo'
      path: '/sistemas/novo'
      fullPath: '/admin/sistemas/novo'
      preLoaderRoute: typeof AdminSistemasNovoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/discord/callback': {
      id: '/auth/discord/callback'
      path: '/auth/discord/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/sistemas/$systemId': {
      id: '/painel/sistemas/$systemId'
      path: '/sistemas/$systemId'
      fullPath: '/painel/sistemas/$systemId'
      preLoaderRoute: typeof PainelSistemasSystemIdRouteImport
      parentRoute: typeof PainelRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientesClientIdRoute: typeof AdminClientesClientIdRoute
  AdminSistemasSystemIdRoute: typeof AdminSistemasSystemIdRoute
  AdminSistemasNovoRoute: typeof AdminSistemasNovoRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminSistemasIndexRoute: typeof AdminSistemasIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientesClientIdRoute: AdminClientesClientIdRoute,
  AdminSistemasSystemIdRoute: AdminSistemasSystemIdRoute,
  AdminSistemasNovoRoute: AdminSistemasNovoRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminSistemasIndexRoute: AdminSistemasIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PainelRouteRouteChildren {
  PainelEstatisticasRoute: typeof PainelEstatisticasRoute
  PainelSuporteRoute: typeof PainelSuporteRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelSistemasSystemIdRoute: typeof PainelSistemasSystemIdRoute
}

const PainelRouteRouteChildren: PainelRouteRouteChildren = {
  PainelEstatisticasRoute: PainelEstatisticasRoute,
  PainelSuporteRoute: PainelSuporteRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelSistemasSystemIdRoute: PainelSistemasSystemIdRoute,
}

const PainelRouteRouteWithChildren = PainelRouteRoute._addFileChildren(
  PainelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PainelRouteRoute: PainelRouteRouteWithChildren,
  ClientRoute: ClientRoute,
  LoginRoute: LoginRoute,
  NoProductsRoute: NoProductsRoute,
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
